# Import Libraries

In [1]:
# load libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
# from sklearn import svm
# from sklearn.neighbors import KNeighborsClassifier
# from sklearn.ensemble import RandomForestClassifier
# from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Load Dataset

In [2]:
loan_data = pd.read_csv("/Users/macbookpro/Desktop/ML & DL & GENAI Projects/Loan Approval Prediction/data/LoanApprovalPrediction.csv")
loan_data

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0.0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1.0,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0.0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0.0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0.0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
593,LP002978,Female,No,0.0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
594,LP002979,Male,Yes,3.0,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
595,LP002983,Male,Yes,1.0,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
596,LP002984,Male,Yes,2.0,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
597,LP002990,Female,No,0.0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

# Data Preprocessing

In [3]:
# first 5 rows
loan_data.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0.0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1.0,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0.0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0.0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0.0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [4]:
# last 5 rows
loan_data.tail()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
593,LP002978,Female,No,0.0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
594,LP002979,Male,Yes,3.0,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
595,LP002983,Male,Yes,1.0,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
596,LP002984,Male,Yes,2.0,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
597,LP002990,Female,No,0.0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [5]:
# check for missing values
loan_data.isnull().sum()

Loan_ID               0
Gender                0
Married               0
Dependents           12
Education             0
Self_Employed         0
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           21
Loan_Amount_Term     14
Credit_History       49
Property_Area         0
Loan_Status           0
dtype: int64

In [6]:
# number of columns of object datatypes
obj = (loan_data.dtypes == 'object')
print("Categorical Columns :", len(list(obj[obj].index)))

Categorical Columns : 7

In [7]:
# drop the Loan_ID column
loan_data.drop(['Loan_ID'], axis=1, inplace=True)
loan_data

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,Male,No,0.0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,Male,Yes,1.0,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,Male,Yes,0.0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,Male,Yes,0.0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,Male,No,0.0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...
593,Female,No,0.0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
594,Male,Yes,3.0,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
595,Male,Yes,1.0,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
596,Male,Yes,2.0,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
597,Female,No,0.0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [8]:
# convert the categorical columns into an int
label_encoder = preprocessing.LabelEncoder()
obj = (loan_data.dtypes == 'object')
for col in list(obj[obj].index):
    loan_data[col] = label_encoder.fit_transform(loan_data[col])

In [9]:
# check number of columns with datatype == object
obj = (loan_data.dtypes == 'object')
print("Categorical Variables :", len(list(obj[obj].index)))

Categorical Variables : 0

In [10]:
# first 5 rows
loan_data.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,1,0,0.0,0,0,5849,0.0,NaN,360.0,1.0,2,1
1,1,1,1.0,0,0,4583,1508.0,128.0,360.0,1.0,0,0
2,1,1,0.0,0,1,3000,0.0,66.0,360.0,1.0,2,1
3,1,1,0.0,1,0,2583,2358.0,120.0,360.0,1.0,2,1
4,1,0,0.0,0,0,6000,0.0,141.0,360.0,1.0,2,1

## Married:       ## Education:             ## Self-Employed
## Yes ==> 1      ## Graduate ==> 0         ## Yes ==> 1
## No ==> 0       ## Not Graduate ==> 1     ## No ==> 0

In [11]:
# check for missing values in columns
for col in loan_data.columns:
  loan_data[col] = loan_data[col].fillna(loan_data[col].mean()) 
 
loan_data.isna().sum()

Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [12]:
# convert the Loan_Status Column Y and N into 1 and 0
loan_data['Loan_Status'] = loan_data['Loan_Status'].replace({
    'Y': 1,
    'N': 0
})

In [13]:
# first 5 rows
loan_data.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,1,0,0.0,0,0,5849,0.0,144.968804,360.0,1.0,2,1
1,1,1,1.0,0,0,4583,1508.0,128.000000,360.0,1.0,0,0
2,1,1,0.0,0,1,3000,0.0,66.000000,360.0,1.0,2,1
3,1,1,0.0,1,0,2583,2358.0,120.000000,360.0,1.0,2,1
4,1,0,0.0,0,0,6000,0.0,141.000000,360.0,1.0,2,1

# Loan Status
## Yes ==> 1
## No ==> 0

In [14]:
# correspondent values of Loan Status column
print(loan_data['Loan_Status'].value_counts())

Loan_Status
1    411
0    187
Name: count, dtype: int64

# Data Splitting

In [15]:
# split the features from the Target
X = loan_data.drop('Loan_Status', axis=1)
y = loan_data['Loan_Status']

In [16]:
# data splitting
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [17]:
# shape of the X and Y
X.shape, y.shape, X_train.shape, X_test.shape, y_train.shape, y_test.shape

((598, 11), (598,), (418, 11), (180, 11), (418,), (180,))

# Model Training

In [18]:
model = LogisticRegression()
model.fit(X_train, y_train)
# classifier = svm.SVC(kernel='linear')
# classifier.fit(X_train, y_train)

/opt/miniconda3/envs/ml_env/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

# Model Evaluation

## Accuracy Score

In [19]:
# accuracy score on training data
# X_train_pred = classifier.predict(X_train)
X_train_pred = model.predict(X_train)
train_data_acc = accuracy_score(X_train_pred, y_train)

In [20]:
# result on the training data
print("Accuracy Score on Training Data: ", train_data_acc)

Accuracy Score on Training Data:  0.8110047846889952

In [21]:
# accuracy score on testing data
# X_test_pred = classifier.predict(X_test)
X_test_pred = model.predict(X_test)
test_data_acc = accuracy_score(X_test_pred, y_test)

In [22]:
# result on the testing data
print("Accuracy Score on Testing Data: ",test_data_acc)

Accuracy Score on Testing Data:  0.7944444444444444

# Predictive System

In [23]:
# input_data = (1,0,0.0,0,0,5849,0.0,144.968804,360.0,1.0,2) # APPROVED
input_data = (1,0,0.0,0,0,5849,0.0,144.968804,360.0,1.0,2) # NOT APPROVED

# change input data into a numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the array for predicting 1 instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = model.predict(input_data_reshaped)
# prediction = classifier.predict(input_data_reshaped)
print(prediction)

if (prediction[0] == 1):
    print("Loan NOT Approved")
else:
    print("Loan APPROVED")

[1]
Loan NOT Approved

/opt/miniconda3/envs/ml_env/lib/python3.13/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

# Save the trained model

In [24]:
# load pickle library
import pickle
# save the model
filename = 'lr_loan_approval_model.sav'
# pickle.dump(classifier, open(filename, 'wb'))
pickle.dump(model, open(filename, 'wb'))
# load the saved model
loaded_model = pickle.load(open('lr_loan_approval_model.sav', 'rb'))